[tools]
"aqua:go-task/task" = "3.53.1"
python = "3.14.4"
pipx = "1.11.1"
ansible = { version = "14.3.1", pipx_args = "--include-deps", uvx = false }
yamllint = "1.38.0"
"pipx:ansible-lint" = "26.8.0"

[env]
ANSIBLE_CONFIG = "{{ config_root }}/ansible/ansible.cfg"

[hooks.postinstall]
run = """
mkdir -p {{ config_root }}/.git/hooks &&
mise generate git-pre-commit > {{ config_root }}/.git/hooks/pre-commit &&
chmod +x {{ config_root }}/.git/hooks/pre-commit
"""

[tasks.pre-commit]
run = "task lint:all"