# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  usb:
    desc: Write preseeded image to a USB device
    interactive: true
    preconditions:
      - sh: test -n '{{.IMG}}'
        msg: 'IMG must be set'
      - sh: test -n '{{.DEVICE}}'
        msg: 'DEVICE must be set'
    cmds:
      - sudo dd if={{.IMG}} of={{.DEVICE}} bs=4M status=progress conv=fsync
  lint:yaml:
    desc: lint yaml files. Lints all yaml files or staged if any
    cmds:
      - |
        STAGED="$(git diff-index --cached --name-only HEAD -- '*.yaml' '*.yml')"
        [ -n "$STAGED" ] && yamllint $STAGED || yamllint .
